Repository ITSM-Project/SLASH-BE, pull requests merged in 2024-10, with the labels that each got.

#4 [FEAT]: 프로젝트 세팅 + jasypt 설정 + entity 구현
  slash/.gitattributes
  slash/.gitignore
  slash/build.gradle
  slash/gradle/wrapper/gradle-wrapper.jar
  slash/gradle/wrapper/gradle-wrapper.properties
  slash/gradlew
  slash/gradlew.bat
  slash/settings.gradle
  slash/src/main/java/project/slash/SlashApplication.java
  slash/src/main/java/project/slash/common/config/JasyptConfig.java
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/repository/ContractRepository.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/serviceassessment/controller/ServiceAssessmentController.java
  slash/src/main/java/project/slash/serviceassessment/model/EvaluationItems.java
  slash/src/main/java/project/slash/serviceassessment/model/ServiceTarget.java
  slash/src/main/java/project/slash/serviceassessment/model/constant/Category.java
  slash/src/main/java/project/slash/serviceassessment/repository/EvaluationItemsRepository.java
  slash/src/main/java/project/slash/serviceassessment/repository/ServiceTargetRepository.java
  slash/src/main/java/project/slash/serviceassessment/service/ServiceAssessmentService.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/java/project/slash/system/controller/SystemController.java
  slash/src/main/java/project/slash/system/model/Equipment.java
  slash/src/main/java/project/slash/system/model/Systems.java
  slash/src/main/java/project/slash/system/repository/EquipmentRepository.java
  slash/src/main/java/project/slash/system/repository/SystemsRepository.java
  slash/src/main/java/project/slash/system/service/SystemService.java
  slash/src/main/java/project/slash/systemincident/controller/SystemIncidentController.java
  slash/src/main/java/project/slash/systemincident/model/SystemIncident.java
  slash/src/main/java/project/slash/systemincident/repository/SystemIncidentRepository.java
  slash/src/main/java/project/slash/systemincident/service/SystemIncidentService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/model/BaseTimeEntity.java
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/java/project/slash/taskrequest/model/TaskType.java
  slash/src/main/java/project/slash/taskrequest/model/constant/RequestStatus.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/java/project/slash/user/controller/UserController.java
  slash/src/main/java/project/slash/user/model/User.java
  slash/src/main/java/project/slash/user/repository/UserRepository.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/main/resources/application.yml
  slash/src/test/java/project/slash/SlashApplicationTests.java
Labels: ✨FEAT, 👷CHORE

#5 [FEAT]: 공통 예외 클래스, 공통 응답 클래스 구현
  slash/build.gradle
  slash/src/main/java/project/slash/common/exception/BusinessException.java
  slash/src/main/java/project/slash/common/exception/CommonExceptionHandler.java
  slash/src/main/java/project/slash/common/exception/ErrorCode.java
  slash/src/main/java/project/slash/common/response/BaseResponse.java
  slash/src/main/java/project/slash/user/exception/UserErrorCode.java
Labels: ✨FEAT

#8 [FEAT]: 계약 생성 기능 구현
  slash/src/main/java/project/slash/contract/constant/Category.java
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/dto/request/CreateContractDto.java
  slash/src/main/java/project/slash/contract/dto/request/EvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/request/ServiceTarget.java
  slash/src/main/java/project/slash/contract/exception/ContractErrorCode.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/model/EvaluationItems.java
  slash/src/main/java/project/slash/contract/model/ServiceTarget.java
  slash/src/main/java/project/slash/contract/repository/EvaluationItemsRepository.java
  slash/src/main/java/project/slash/contract/repository/ServiceTargetRepository.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/serviceassessment/controller/ServiceAssessmentController.java
  slash/src/main/java/project/slash/serviceassessment/model/EvaluationItems.java
  slash/src/main/java/project/slash/serviceassessment/model/constant/Category.java
  slash/src/main/java/project/slash/serviceassessment/service/ServiceAssessmentService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/CreateTaskTypeDto.java
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/java/project/slash/taskrequest/model/TaskType.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/resources/application-test.yml
  slash/src/test/java/project/slash/contract/constant/CategoryTest.java
Labels: ✨FEAT, 🧪TEST

#9 [FEAT]: 업무 요청 생성 기능 구현
  slash/.gitignore
  slash/build.gradle
  slash/src/main/java/project/slash/common/config/QuerydslConfig.java
  slash/src/main/java/project/slash/common/exception/CommonExceptionHandler.java
  slash/src/main/java/project/slash/system/controller/SystemController.java
  slash/src/main/java/project/slash/system/dto/response/AllSystemsInfo.java
  slash/src/main/java/project/slash/system/dto/response/EquipmentInfo.java
  slash/src/main/java/project/slash/system/exception/SystemsErrorCode.java
  slash/src/main/java/project/slash/system/model/Equipment.java
  slash/src/main/java/project/slash/system/model/Systems.java
  slash/src/main/java/project/slash/system/repository/SystemsRepository.java
  slash/src/main/java/project/slash/system/repository/SystemsRepositoryCustom.java
  slash/src/main/java/project/slash/system/repository/SystemsRepositoryImpl.java
  slash/src/main/java/project/slash/system/service/SystemService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/CreateTaskTypeDto.java
  slash/src/main/java/project/slash/taskrequest/dto/request/TaskRequestDto.java
  slash/src/main/java/project/slash/taskrequest/exception/TaskRequestErrorCode.java
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/java/project/slash/taskrequest/model/TaskType.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/resources/application-test.yml
  slash/src/main/resources/application.yml
  slash/src/test/java/project/slash/system/repository/SystemsRepositoryTest.java
  slash/src/test/java/project/slash/taskrequest/repository/TaskTypeRepositoryTest.java
Labels: ✨FEAT, 🧪TEST, 👷CHORE

#12 [FEAT] 시큐리티 로그인/역할별 RESTAPI 구현
  slash/build.gradle
  slash/src/main/java/project/slash/security/auth/CustomUserDetailService.java
  slash/src/main/java/project/slash/security/auth/CustomUserDetails.java
  slash/src/main/java/project/slash/security/auth/UserAuthFailureHandler.java
  slash/src/main/java/project/slash/security/auth/UserAuthSuccessHandler.java
  slash/src/main/java/project/slash/security/config/SecurityConfig.java
  slash/src/main/java/project/slash/user/controller/UserController.java
  slash/src/main/java/project/slash/user/model/User.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, 👷CHORE

#17 [FEAT] 시큐리티 세션 생성
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
  slash/src/main/java/project/slash/security/auth/CustomUserDetailService.java
  slash/src/main/java/project/slash/security/auth/CustomUserDetails.java
  slash/src/main/java/project/slash/user/controller/UserController.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, ♻️REFACTOR, 🔥REMOVE

#23 [FEAT]: 계약 생성 기능 수정
  slash/build.gradle
  slash/src/main/java/project/slash/common/exception/CommonExceptionHandler.java
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/contract/dto/ContractDto.java
  slash/src/main/java/project/slash/contract/dto/GradeDto.java
  slash/src/main/java/project/slash/contract/dto/request/CreateContractDto.java
  slash/src/main/java/project/slash/contract/dto/request/DetailDto.java
  slash/src/main/java/project/slash/contract/dto/request/EvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/request/ServiceTarget.java
  slash/src/main/java/project/slash/contract/dto/response/ContractInfoDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/response/ServiceDetailDto.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/model/EvaluationItems.java
  slash/src/main/java/project/slash/contract/model/ServiceDetail.java
  slash/src/main/java/project/slash/contract/model/ServiceTarget.java
  slash/src/main/java/project/slash/contract/model/TotalTarget.java
  slash/src/main/java/project/slash/contract/repository/ContractRepository.java
  slash/src/main/java/project/slash/contract/repository/EvaluationItemsRepository.java
  slash/src/main/java/project/slash/contract/repository/ServiceDetailRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/system/controller/SystemController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/CreateTaskTypeDto.java
  slash/src/main/java/project/slash/taskrequest/dto/request/TaskRequestDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/TaskTypeDto.java
  slash/src/main/java/project/slash/taskrequest/model/TaskType.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/resources/application.yml
  slash/src/test/java/project/slash/contract/constant/CategoryTest.java
  slash/src/test/java/project/slash/taskrequest/repository/TaskTypeRepositoryTest.java
Labels: ✨FEAT, 💄STYLE, ♻️REFACTOR

#25 [FEAT]: 서비스 항목 별 세부 내용 조회 기능 구현
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/contract/dto/GradeDto.java
  slash/src/main/java/project/slash/contract/dto/TaskTypeDto.java
  slash/src/main/java/project/slash/contract/dto/request/CreateContractDto.java
  slash/src/main/java/project/slash/contract/dto/request/CreateDetailDto.java
  slash/src/main/java/project/slash/contract/dto/response/ContractDto.java
  slash/src/main/java/project/slash/contract/dto/response/ContractInfoDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDetailDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/response/ServiceDetailDto.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/model/ServiceDetail.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/response/AllTaskTypeDto.java
  slash/src/main/java/project/slash/taskrequest/model/TaskType.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, 💄STYLE

#28 [FEAT]: 요청 내역 상세 조회하기 구현
  slash/src/main/java/project/slash/contract/dto/GradeDto.java
  slash/src/main/java/project/slash/contract/dto/response/ContractDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDetailDto.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/model/TotalTarget.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/system/model/Equipment.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/TaskRequestDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/AllTaskTypeDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/RequestDetailDto.java
  slash/src/main/java/project/slash/taskrequest/exception/TaskRequestErrorCode.java
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/java/project/slash/taskrequest/model/constant/RequestStatus.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: ✨FEAT, ♻️REFACTOR

#29 [FEAT]: RequestManager메인 상단 백엔드 구현
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/response/RequestManagerMainResponseDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/StatusCountDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/StatusCountResponseDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/SystemCountDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/TaskTypeCountDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: 🔧 FIX, ✨FEAT, 💄STYLE

#33 [REFACTOR]: 상태처리별 건수 반환 코드 리팩터링 및 충돌 해결
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/response/RequestManagerMainResponseDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/StatusCountDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/StatusCountResponseDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: 🔧 FIX, ♻️REFACTOR, 🔥REMOVE
