Repository ITSM-Project/SLASH-BE, pull requests merged in 2024-11, with the labels that each got.

#41 [REFACTOR]: 업무 유형 조회 관련 기능 TaskRequest랑 분리
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/dto/request/ContractRequestDto.java
  slash/src/main/java/project/slash/contract/dto/response/PreviewEvaluationItemDto.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/repository/TotalTargetRepository.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/evaluationitem/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/evaluationitem/dto/TaskTypeDto.java
  slash/src/main/java/project/slash/evaluationitem/dto/request/CreateEvaluationItemDto.java
  slash/src/main/java/project/slash/evaluationitem/dto/response/EvaluationItemDto.java
  slash/src/main/java/project/slash/evaluationitem/model/ServiceTarget.java
  slash/src/main/java/project/slash/evaluationitem/repository/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/evaluationitem/service/EvaluationItemService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskTypeController.java
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/java/project/slash/taskrequest/service/TaskTypeService.java
  slash/src/main/resources/application.yml
Labels: ♻️REFACTOR, 🔥REMOVE

#38 [REFACTOR]: 통계테이블 칼럼 추가
  slash/src/main/java/project/slash/statistics/model/Statistics.java
Labels: ♻️REFACTOR

#30 [FEAT]: Security 설정 / JsonWebToken 인증 방식 구현
  slash/build.gradle
  slash/src/main/java/project/slash/common/config/CorsConfig.java
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/security/auth/UserAuthFailureHandler.java
  slash/src/main/java/project/slash/security/auth/UserAuthSuccessHandler.java
  slash/src/main/java/project/slash/security/auth/custom/CustomUserDetailService.java
  slash/src/main/java/project/slash/security/auth/custom/CustomUserDetails.java
  slash/src/main/java/project/slash/security/auth/dto/JwtTokenDto.java
  slash/src/main/java/project/slash/security/auth/dto/LoginRequestDto.java
  slash/src/main/java/project/slash/security/auth/filter/JwtAuthenticationFilter.java
  slash/src/main/java/project/slash/security/auth/provider/JwtTokenProvider.java
  slash/src/main/java/project/slash/security/auth/service/AuthService.java
  slash/src/main/java/project/slash/security/auth/service/AuthServiceImpl.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskTypeController.java
  slash/src/main/java/project/slash/user/controller/UserController.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/main/resources/application.yml
Labels: 🔧 FIX, ✨FEAT, 👷CHORE, 🔥REMOVE

#46 [FEAT]: 서비스 가동률 자동계산 통계 구현
  slash/src/main/java/project/slash/contract/dto/ContractDataDto.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/MonthlyDataDto.java
  slash/src/main/java/project/slash/statistics/dto/MonthlyServiceStatsDto.java
  slash/src/main/java/project/slash/statistics/dto/StatsDto.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
Labels: ✨FEAT, ♻️REFACTOR

#44 [FEAT]: 계약 관련 기능 수정
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/contract/dto/GradeDto.java
  slash/src/main/java/project/slash/contract/dto/TaskTypeDto.java
  slash/src/main/java/project/slash/contract/dto/request/CreateEvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/response/ContractDetailDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDetailDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDto.java
  slash/src/main/java/project/slash/contract/exception/EvaluationItemErrorCode.java
  slash/src/main/java/project/slash/contract/mapper/ContractMapper.java
  slash/src/main/java/project/slash/contract/mapper/ServiceTargetMapper.java
  slash/src/main/java/project/slash/contract/mapper/TotalTargetMapper.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/model/ServiceTarget.java
  slash/src/main/java/project/slash/contract/repository/ContractRepository.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/repository/ServiceTargetRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/evaluationitem/dto/ServiceTargetDto.java
  slash/src/main/java/project/slash/evaluationitem/dto/response/EvaluationItemDetailDto.java
  slash/src/main/java/project/slash/evaluationitem/dto/response/EvaluationItemDto.java
  slash/src/main/java/project/slash/evaluationitem/repository/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/evaluationitem/repository/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/system/model/Systems.java
  slash/src/main/java/project/slash/system/service/SystemService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/response/RequestDetailDto.java
  slash/src/main/java/project/slash/taskrequest/mapper/TaskTypeMapper.java
  slash/src/main/java/project/slash/taskrequest/model/TaskType.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/test/java/project/slash/contract/repository/ContractRepositoryTest.java
  slash/src/test/java/project/slash/system/repository/SystemsRepositoryTest.java
Labels: ♻️REFACTOR, 🧪TEST

#49 [FIX] 공통 URN 추가
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
  slash/src/main/java/project/slash/user/service/UserService.java
Labels: 🔧 FIX

#45 [FEAT] : 요청 관리 표 기능 구현
  slash/src/main/java/project/slash/common/response/BaseResponse.java
  slash/src/main/java/project/slash/contract/repository/ContractRepository.java
  slash/src/main/java/project/slash/system/controller/SystemController.java
  slash/src/main/java/project/slash/system/repository/SystemsRepository.java
  slash/src/main/java/project/slash/system/service/SystemService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskTypeController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/RequestManagementDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/RequestManagementResponseDto.java
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/java/project/slash/taskrequest/service/TaskTypeService.java
  slash/src/main/resources/application-test.yml
Labels: 🔧 FIX, ✨FEAT, 💄STYLE, ♻️REFACTOR

#52 [FEAT]: 담당자별 업무 현황 리스트 조회 및 할당, 통계, 상태 변경
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/MonthlyDataDto.java
  slash/src/main/java/project/slash/statistics/dto/MonthlyServiceStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/StatisticsDto.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/UpdateTaskRequestManagerDto.java
  slash/src/main/java/project/slash/taskrequest/dto/response/TaskRequestOfManagerDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/java/project/slash/user/service/UserService.java
Labels: ✨FEAT

#51 :sparkles: FEAT: 요청관리 API에 요청자 ID추가
  slash/src/main/java/project/slash/taskrequest/dto/request/RequestManagementDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
Labels: ✨FEAT

#55 :sparkles: [REFACTOR]: api주소 변경
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: ♻️REFACTOR

#61 [FIX]: 권한별 url 변경
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskTypeController.java
Labels: 🔧 FIX

#63 [REFACTOR]: 요청 타입 관련 url 권한 추가
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: 🔧 FIX, ♻️REFACTOR

#64 [FIX]: 할당 리스트 쿼리 수정
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
Labels: 🔧 FIX

#77 [FIX] : 요청 관리표에서 요청 상세에 같은 id 값 나오는 오류 수정
  slash/src/main/java/project/slash/taskrequest/dto/request/RequestManagementDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
Labels: 🔧 FIX

#74 [FEAT]: 업무 유형 조회 시 특정 계약에 해당하는 업무 유형만 조회하도록 변경
  slash/src/main/java/project/slash/common/config/WebConfig.java
  slash/src/main/java/project/slash/contract/dto/request/ContractRequestDto.java
  slash/src/main/java/project/slash/contract/dto/response/AllContractDto.java
  slash/src/main/java/project/slash/contract/dto/response/ContractDetailDto.java
  slash/src/main/java/project/slash/contract/mapper/ContractMapper.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/security/annotation/Login.java
  slash/src/main/java/project/slash/security/annotation/LoginArgumentResolver.java
  slash/src/main/java/project/slash/security/exception/AuthErrorCode.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskTypeController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/TaskRequestDto.java
  slash/src/main/java/project/slash/taskrequest/dto/request/UpdateTaskRequestManagerDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/java/project/slash/taskrequest/service/TaskTypeService.java
  slash/src/main/java/project/slash/user/controller/UserController.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/main/resources/application.yml
Labels: ♻️REFACTOR

#90 [FEAT]: 계약 수정 기능 구현
  slash/src/main/java/project/slash/contract/controller/ContractController.java
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/contract/dto/request/CreateEvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemDetailDto.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/model/TotalTarget.java
  slash/src/main/java/project/slash/contract/repository/ServiceTargetRepository.java
  slash/src/main/java/project/slash/contract/repository/TotalTargetRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepository.java
  slash/src/main/java/project/slash/user/service/UserService.java
Labels: ✨FEAT, ♻️REFACTOR

#93 [FEAT]: 통계 계산, 미계산 지표 조회 기능 + 추가 필요한 기능
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/contract/dto/request/CreateEvaluationItemDto.java
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemCategoryDto.java
  slash/src/main/java/project/slash/contract/mapper/EvaluationItemMapper.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepository.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/request/EditStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/CalculatedStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/IndicatorDto.java
  slash/src/main/java/project/slash/statistics/dto/response/StatisticsStatusDto.java
  slash/src/main/java/project/slash/statistics/dto/response/UnCalculatedStatisticsDto.java
  slash/src/main/java/project/slash/statistics/exception/StatisticsErrorCode.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, ♻️REFACTOR, 👷CHORE

#95 [FEAT]: 계약 종료 스케줄러 구현
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/repository/ContractRepository.java
  slash/src/main/java/project/slash/contract/service/ContractSchedulingService.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
Labels: ✨FEAT

#76 [FEAT]: 서비스요청 통계 서비스 로직 구현
  slash/src/main/java/project/slash/contract/repository/ServiceTargetRepository.java
  slash/src/main/java/project/slash/statistics/controller/ServiceStaticsController.java
  slash/src/main/java/project/slash/statistics/dto/request/RequestStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/ResponseServiceTaskDto.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
Labels: ✨FEAT

#100 [FIX]: 충돌 해결
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
Labels: 🔧 FIX

#101 [FEAT]: 지표 통계 결과 조회 기능 구현
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/MonthlyServiceStatisticsDto.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
Labels: ✨FEAT

#89 [FEAT]: 장애적기처리율 서비스 로직 구현
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/controller/IncidentTaskController.java
  slash/src/main/java/project/slash/statistics/dto/GradeScoreDto.java
  slash/src/main/java/project/slash/statistics/dto/IncidentInfoDto.java
  slash/src/main/java/project/slash/statistics/dto/request/RequestStatisticsDto.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/user/controller/UserController.java
Labels: ✨FEAT, ♻️REFACTOR

#105 [REFACTOR]: 브랜치 변경하여 서비스 가동률 자동계산 및 리팩토링
  slash/src/main/java/project/slash/contract/dto/response/ContractDataDto.java
  slash/src/main/java/project/slash/contract/repository/ContractRepository.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/response/EvaluatedDto.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyDataDto.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyServiceStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/StatisticsDto.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, ♻️REFACTOR

#106 [FEAT]: 한달 주기로 통계 지표 계산하는 스케줄러 구현
  slash/src/main/java/project/slash/contract/dto/request/CreateEvaluationItemDto.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/repository/ContractRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/contract/ContractRepository.java
  slash/src/main/java/project/slash/contract/repository/contract/ContractRepositoryCustom.java
  slash/src/main/java/project/slash/contract/repository/contract/ContractRepositoryCustomImpl.java
  slash/src/main/java/project/slash/contract/service/ContractSchedulingService.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/request/RequestStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/IndicatorDto.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyServiceStatisticsDto.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/statistics/service/StatisticsSchedulingService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/test/java/project/slash/contract/repository/ContractRepositoryTest.java
Labels: ✨FEAT

#107 [REFACTOR] 서비스 요청 적기처리율 데이터 디폴트값 변경
  slash/src/main/java/project/slash/statistics/dto/response/ResponseStatisticsDto.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
Labels: ♻️REFACTOR

#81 [REFACTOR]: 처리 완료시 테이블 업데이트 및 장애 요청건에 한해 SystemIncident테이블에 추가
  slash/src/main/java/project/slash/systemincident/model/SystemIncident.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: 🔧 FIX, ♻️REFACTOR

#114 Revert "[REFACTOR]: 처리 완료시 테이블 업데이트 및 장애 요청건에 한해 SystemIncident테이블에 추가"
  slash/src/main/java/project/slash/systemincident/model/SystemIncident.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: ♻️REFACTOR

#109 [REFACTOR]: 통계 관련 조회 기능 수정
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/response/CalculatedStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/IndicatorDto.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyServiceStatisticsDto.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
Labels: 🔧 FIX, ♻️REFACTOR

#113 [REFACTOR]: 예외 발생 처리 추가, 로그인시 JWT 인증 스킵, 장애 적기처리율 기본 생성 데이터 수정
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustom.java
  slash/src/main/java/project/slash/security/auth/filter/JwtAuthenticationFilter.java
  slash/src/main/java/project/slash/security/auth/provider/JwtTokenProvider.java
  slash/src/main/java/project/slash/security/auth/service/AuthServiceImpl.java
  slash/src/main/java/project/slash/statistics/model/Statistics.java
  slash/src/main/java/project/slash/user/service/UserService.java
  slash/src/main/resources/application.yml
Labels: ♻️REFACTOR

#117 [REFACTOR]: 처리 완료시 테이블 업데이트 및 장애 요청건에 한해 SystemIncident테이블에 추가
  slash/src/main/java/project/slash/systemincident/model/SystemIncident.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: ♻️REFACTOR

#118 [REFACTOR] : 월별 지표 조회 기능 수정 + 자동 계산 통계 로직 파일 이동
  slash/src/main/java/project/slash/statistics/controller/IncidentTaskController.java
  slash/src/main/java/project/slash/statistics/controller/ServiceStatisticsController.java
  slash/src/main/java/project/slash/statistics/controller/ServiceUptimeController.java
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepository.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsSchedulingService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
Labels: ♻️REFACTOR

#119 [FIX]: 장애적기처리율 오류 수정
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
Labels: 🔧 FIX

#123 [REFACTOR]: 필요없는 값 -1, calculate_time추가
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
Labels: ♻️REFACTOR

#126 [FEAT]: 통계 삭제 기능 구현
  slash/src/main/java/project/slash/statistics/controller/StatisticsController.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
Labels: ✨FEAT

#124 [FEAT]: 한달 통계 pdf 다운로드 기능 구현
  slash/build.gradle
  slash/src/main/java/project/slash/statistics/controller/PdfController.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyServiceStatisticsDto.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/service/PdfService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsService.java
  slash/src/main/resources/application.yml
  slash/src/main/resources/static/fonts/NanumGothic-Regular.ttf
  slash/src/main/resources/templates/evaluationItem.html
Labels: ✨FEAT

#128 [REFACTOR]: 서비스 적기 처리율 통계 파람 타입 변경
  slash/src/main/java/project/slash/statistics/controller/ServiceStatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/response/ResponseStatisticsDto.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
Labels: ♻️REFACTOR

#136 [FIX]: DB csv Import 를 위한 설정 변경
  slash/src/main/java/project/slash/taskrequest/model/TaskRequest.java
  slash/src/main/resources/application.yml
Labels: 🔧 FIX

#131 [FEAT]: 장애 적기 처리율 조회 기능 추가
  slash/src/main/java/project/slash/statistics/controller/IncidentTaskController.java
  slash/src/main/java/project/slash/statistics/dto/response/ResponseStatisticsDto.java
  slash/src/main/java/project/slash/statistics/mapper/StatisticsMapper.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsSchedulingService.java
Labels: 🔧 FIX, ✨FEAT

#138 [REFACTOR]: 계약아이디 추가 및유저 페이지 계약 아이디, 연,월 별 처리 상태 건수 조회 구현
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: ✨FEAT, ♻️REFACTOR

#139 [REFACTOR]: 서비스 요청 적기 처리율 리스폰스 데이트 추가
  slash/src/main/java/project/slash/statistics/dto/response/ResponseStatisticsDto.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
Labels: ♻️REFACTOR

#141 [FEAT]: 요청 관리 로직에 날짜 년월(required false) , 계약아이디, 계약자 권한이면 자기 요청만 볼 수 있게 설정
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/RequestManagementDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: ✨FEAT

#143 [FIX]: 요청 필터링 기능 오류 수정
  slash/src/main/java/project/slash/statistics/controller/IncidentTaskController.java
  slash/src/main/java/project/slash/system/model/Systems.java
  slash/src/main/java/project/slash/taskrequest/controller/TaskRequestController.java
  slash/src/main/java/project/slash/taskrequest/dto/request/RequestManagementDto.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustom.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskRequestRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
  slash/src/main/resources/templates/evaluationItem.html
Labels: 🔧 FIX

#146 [REFACTOR]: 통계 reponseDTO 타입변경
  slash/src/main/java/project/slash/statistics/controller/IncidentTaskController.java
  slash/src/main/java/project/slash/statistics/controller/ServiceStatisticsController.java
  slash/src/main/java/project/slash/statistics/dto/request/RequestStatisticsDto.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsSchedulingService.java
Labels: ♻️REFACTOR

#147 [FEAT]: 서비스 가동률 데이트 포맷 수정
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, ♻️REFACTOR

#151 [FEAT]: 계약 관련 기능 테스트 코드 작성
  slash/build.gradle
  slash/src/main/java/project/slash/contract/dto/request/ContractRequestDto.java
  slash/src/main/java/project/slash/contract/model/Contract.java
  slash/src/main/java/project/slash/contract/repository/contract/ContractRepository.java
  slash/src/main/java/project/slash/contract/service/ContractService.java
  slash/src/main/java/project/slash/user/model/User.java
  slash/src/test/java/project/slash/contract/controller/ContractControllerTest.java
  slash/src/test/java/project/slash/contract/repository/ContractRepositoryTest.java
  slash/src/test/java/project/slash/contract/service/ContractServiceTest.java
Labels: 🧪TEST

#153 [REFACTOR]: 서비스 가동률 반환 dto 를 ResponseStatisticsDto 로 통일 및 서비스 메서드 명 변경
  slash/src/main/java/project/slash/statistics/controller/ServiceUptimeController.java
  slash/src/main/java/project/slash/statistics/dto/response/MonthlyStatisticsDto.java
  slash/src/main/java/project/slash/statistics/dto/response/ResponseStatisticsDto.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustom.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
  slash/src/main/java/project/slash/statistics/service/StatisticsSchedulingService.java
Labels: ♻️REFACTOR

#154 [TEST]: 서비스 평가 항목 관련 테스트 코드 작성
  slash/src/main/java/project/slash/contract/dto/response/EvaluationItemCategoryDto.java
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
  slash/src/test/java/project/slash/contract/controller/EvaluationItemControllerTest.java
  slash/src/test/java/project/slash/contract/service/ContractServiceTest.java
  slash/src/test/java/project/slash/contract/service/EvaluationItemServiceTest.java
Labels: 🧪TEST

#164 [REFACTOR]: 계산, 미계산 지표 조회 시 계약 조건 추가
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
Labels: ♻️REFACTOR

#167 [FEAT]: CI/CD 도커파일 생성 및 설정 추가
  slash/.gitignore
  slash/Dockerfile
  slash/src/main/java/project/slash/common/controller/HealthCheckController.java
  slash/src/main/resources/application.yml
Labels: ✨FEAT, ♻️REFACTOR

#166 [FEAT]: CICD yml 생성
  .github/workflows/gradle.yml
Labels: ✨FEAT

#168 [REFACTOR]: gradle.yml 오류수정
  .github/workflows/gradle.yml
Labels: ♻️REFACTOR

#169 [REFACTOR]: gradle.yml 오타 수정
  .github/workflows/gradle.yml
Labels: ♻️REFACTOR

#170 [REFACTOR]: CI/CD 테스트
  .github/workflows/ slash-workflow.yml
  slash/Dockerfile
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
  slash/src/main/java/project/slash/security/auth/filter/JwtAuthenticationFilter.java
Labels: ♻️REFACTOR

#173 [FIX]: PR시 배포 수정
  .github/workflows/ slash-workflow.yml
Labels: 🔧 FIX

#175 [FIX]: 배포 수정
  .github/workflows/ slash-workflow.yml
Labels: 🔧 FIX

#163 [REFACTOR]: 총가중치 반영 쿼리 수정
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/resources/application.yml
Labels: ♻️REFACTOR

#171 [REFACTOR] 서비스 요청 적기 처리율 통계 로직 수정
  slash/src/main/java/project/slash/statistics/dto/response/ResponseServiceTaskDto.java
  slash/src/main/java/project/slash/statistics/repository/StatisticsRepositoryCustomImpl.java
  slash/src/main/java/project/slash/statistics/service/AutoStatisticsService.java
Labels: 🔧 FIX, ♻️REFACTOR

#177 [FEAT]: 요청 관련 오류 수정
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/repository/TaskTypeRepositoryCustomImpl.java
  slash/src/main/java/project/slash/taskrequest/service/TaskRequestService.java
Labels: 🔧 FIX, ♻️REFACTOR

#179 [FEAT]: 기본적인 서비스 평가 항목 내용 조회 기능 구현
  slash/src/main/java/project/slash/contract/controller/EvaluationItemController.java
  slash/src/main/java/project/slash/contract/dto/response/DefaultEvaluationItemDto.java
  slash/src/main/java/project/slash/contract/mapper/EvaluationItemMapper.java
  slash/src/main/java/project/slash/contract/repository/evaluationItem/EvaluationItemRepository.java
  slash/src/main/java/project/slash/contract/service/EvaluationItemService.java
Labels: ✨FEAT

#181 [FIX]: 파일 이름 오타 수정
  .github/workflows/slash-workflow.yml
Labels: 🔧 FIX

#184 [FIX]: 서비스 평가 항목 업데이트 기능 오류 수정
  slash/src/main/java/project/slash/contract/model/EvaluationItem.java
  slash/src/main/resources/application-test.yml
Labels: 🔧 FIX

#186 [REFACTOR]: CORS설정 추가
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
Labels: ♻️REFACTOR

#188 [REFACTOR]: 프론트 서브도메인 추가
  slash/src/main/java/project/slash/common/config/SecurityConfig.java
Labels: ♻️REFACTOR
